### ISSUE TITLE
Breadcrumbs dissappear

### ISSUE THREAD

**Issue by WPwithGTuser** [sky4git/Connect-Genesis-WooCommerce#1]
Hi,
interesting plugin. Unfortunately when I installed your plugin "Woocommerce with Genesis" on the latest WP 4.4.2 & woocommerce 2.5.2, and as soon as I activated the plugin the breadcrumbs in woocommerce disappeared, even though all options were turned off in your plugin. Note breadcrumbs still appear in the news section of my website, but no longer in woocommerce for my products or product categories. Deactivating the plugin brings back the breadcrumbs. Note that I had deactivated all other plugins apart from woocommerce, but the problem still remains.

**Comment by WPwithGTuser** [comment]
Note I am using the Grind child theme 2.2.6 with the latest version of Genesis. Also I have tried turning on the first few settings in your plugin, and tried selecting the "modfiy breadcrumbs" settings, but that didnt bring back the breadcrumbs.

**Comment by WPwithGTuser** [comment]
Am I supposed to be using the "Genesis Connect for WooCommerce" plugin as well as your plugin to make this work?

**Comment by WPwithGTuser** [comment]
accidentally closed the issue, so have reopend it now as it is still an issue.

**Comment by sky4git** [comment]
I will have a look. Thanks for informing me. 
This plugin should work independently, but surely can't work if "Genesis Connect for WooCommerce"  is also activated.

**Comment by WPwithGTuser** [comment]
Thanks a lot, much appreciated,

Regards

Mark Spencer
IT and Administration

> > M (+61 439) 176 130
> > E mark@morse.com.aumailto:mark@morse.com.au
> > W www.morse.com.auhttp://www.morse.com.au/

See our latest Product Cataloguehttp://morse.com.au/morse-power-publications

[cid:image001.png@01D15F9D.AFF861D0]

[cid:image002.png@01D15F9D.AFF861D0]http://www.linkedin.com/company/morse-engineering/

**Comment by sky4git** [comment]
The plugin disables "woocommerce breadcrumbs" by default. This behaviour needs to be changed.
I will make an option for it in the next version update.
For now, You can comment out line number 176: or below code
`$this->loader->add_action( 'get_header', $plugin_public, 'genwoo_remove_breadcrumb' );`
from plugins **connect-genesis-woocommerce/includes/class-genesis-woocommerce.php**

Please let me know if it helps.

**Comment by WPwithGTuser** [comment]
Hi,

Thanks for the workaround. Additionally in our next version you may want to consider adding the ability to change the text of the “Additional Information” tab heading (similar to what you have done for Product Information tab heading).

Regards

Mark Spencer
IT and Administration

> > M (+61 439) 176 130
> > E mark@morse.com.aumailto:mark@morse.com.au
> > W www.morse.com.auhttp://www.morse.com.au/

See our latest Product Cataloguehttp://morse.com.au/morse-power-publications

[cid:image001.png@01D16028.DC440A60]

[cid:image002.png@01D16028.DC440A60]http://www.linkedin.com/company/morse-engineering/

**Comment by sky4git** [comment]
#3c1016a commit.
