### ISSUE TITLE
Version3 - some issues

### ISSUE THREAD

**Issue by WPwithGTuser** [sky4git/Connect-Genesis-WooCommerce#2]
Hi,

Tried your new version 3, thanks for the changes, except these are the issues i had on both sites where I tried it, sites were unfortunately broken until I rolled back to version2.1 (all other plugins disabled except woocoomerce):

1) The 3 tabs - Reviews etc, display in reverse order.
2) I can no longer hide those tabs if I select "hide" for each tab.
3) Empty tabs display a long error message under each tab heading on the front end to the website user:
"Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in /home/morsewin/public_html/wp-content/plugins/woocommerce/templates/single-product/tabs/tabs.php on line 42"

thanks for your time,

**Comment by sky4git** [comment]
I will check it promptly!

**Comment by WPwithGTuser** [comment]
Thanks heaps,

Regards

Mark Spencer
IT and Administration

> > M (+61 439) 176 130
> > E mark@morse.com.aumailto:mark@morse.com.au
> > W www.morse.com.auhttp://www.morse.com.au/

See our latest Product Cataloguehttp://morse.com.au/morse-power-publications

[cid:image001.png@01D16CE1.482DFD70]

[cid:image002.png@01D16CE1.482DFD70]http://www.linkedin.com/company/morse-engineering/

**Comment by sky4git** [comment]
My initial research indicate that issue is related to [https://gist.github.com/jameskoster/5133515]
I am going to add more checks for tabs. Wait for the code update!

**Comment by sky4git** [comment]
Please try out new code from github and let me know.

**Comment by WPwithGTuser** [comment]
Hi, where do I find the new code on github to try?

Regards

Mark Spencer
IT and Administration

> > M (+61 439) 176 130
> > E mark@morse.com.aumailto:mark@morse.com.au
> > W www.morse.com.auhttp://www.morse.com.au/

See our latest Product Cataloguehttp://morse.com.au/morse-power-publications

[cid:image001.png@01D16D44.DE83AC30]

[cid:image002.png@01D16D44.DE83AC30]http://www.linkedin.com/company/morse-engineering/

**Comment by sky4git** [comment]
Please download zip file from https://github.com/sky4git/Connect-Genesis-WooCommerce.

**Comment by WPwithGTuser** [comment]
Thanks, will have to look at it tomorrow when more time as is a manual install and to do the testing,

Regards

Mark Spencer
IT and Administration

> > M (+61 439) 176 130
> > E mark@morse.com.aumailto:mark@morse.com.au
> > W www.morse.com.auhttp://www.morse.com.au/

See our latest Product Cataloguehttp://morse.com.au/morse-power-publications

[cid:image001.png@01D16D47.78670CA0]

[cid:image002.png@01D16D47.78670CA0]http://www.linkedin.com/company/morse-engineering/
