### ISSUE TITLE
WP Multisite...

### ISSUE THREAD

**Issue by ghost** [sky4git/Connect-Genesis-WooCommerce#3]
Hi,
I'm using your plugin on a multisite install, but it does not appear to see that woo-commerce is network activated...

_"Activate WooCommerce plugin to run WooCommerce Customizer(with Genesis support) plugin smoothly!"_

Thanks
![customizer triple scented candles wordpress 2016-10-23 11-09-46](https://cloud.githubusercontent.com/assets/2083126/19622882/6c33cd8c-9911-11e6-8d67-c361022e33be.jpg)

**Comment by sky4git** [comment]
Currently, plugin doesn't support multisite. Its something I want to implement in future version.  Although you can try below code change  in the plugin to see if it works.

**in /connect-genesis-woocommerce/includes/class-genesis-woocommerce-loader.php replace line number 51 to 59**

`/** Fail silently if WooCommerce is not activated */
    /*  if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) )  ){
            add_action( 'admin_notices', array($this, 'genwoo_admin_notice') );
            //\deactivate_plugins( plugin_basename( __FILE__ ) );
            return;
        }else{ */
            $this->actions = array();
            $this->filters = array();
    //  }`

**Comment by ghost** [comment]
Thanks for the quick reply.

That seems to work for the moment!

---

_Peter Williamson_
Developer.
peter@t1.co.nz
Skype: t1peter

On 23 October 2016 at 1:44:04 PM, Sky4git (notifications@github.com) wrote:

/*\* Fail silently if WooCommerce is not activated _/
/_ if ( ! in_array( 'woocommerce/woocommerce.php', apply_filters(
'active_plugins', get_option( 'active_plugins' ) ) ) ){
add_action( 'admin_notices', array($this, 'genwoo_admin_notice') );
//\deactivate_plugins( plugin_basename( **FILE** ) );
return;
}else{ */
$this->actions = array();
$this->filters = array();
// }
